### ISSUE TITLE
Create Bids

### ISSUE THREAD

**Issue by whiterook6** [whiterook6/babypool#2]
to do:

- create migration, model for bids:

```
Bid:
 - bidder_id: fk on bidder.id
 - value: unsigned integer
 - date
 - confirmed: boolean
 - timestamps
```

Includes foreign key for bidders
